const { resolve } = require('path')
const { homedir } = require('os')
const mkdirp = require('mkdirp')
const fs = require('fs')

exports.command = 'init [dir]'

exports.describe = 'Creates the local iotame configuration directory'

exports.builder = {
  dir: {
    default: process.cwd(),
    describe: 'The directory to create the iotame base at'
  }
}

exports.handler = function (argv) {
  let pkg = {
    name: 'iotame-extensions',
    description: 'Auto-generated by iotame',
    private: true,
    version: '1.0.0',
    repository: 'iotame/iotame',
    license: 'CC-BY-4.0',
    homepage: 'https://iotame.cloud',
    dependencies: {
      '@iotame/builtins': '>=0.0.1-b'
    }
  }

  let ext = {
    loaded: [ "@iotame/builtins" ]
  }

  mkdirp.sync(resolve(argv.dir, 'logs'))
  mkdirp.sync(resolve(argv.dir, 'extensions', 'local'))
  mkdirp.sync(resolve(argv.dir, 'config'))

  let pkgPath = resolve(argv.dir, 'extensions', 'package.json')
  if (!fs.existsSync(pkgPath)) {
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2))
  }

  let extPath = resolve(argv.dir, 'config', 'extensions.json')
  if (!fs.existsSync(extPath)) {
    fs.writeFileSync(extPath, JSON.stringify(ext, null, 2))
  }
}
